import markdown
from weasyprint import HTML, CSS
from datetime import datetime
import os

class PDFGenerator:
    """Generate beautiful PDFs from markdown itineraries"""

    def __init__(self):
        self.output_dir = "output"
        os.makedirs(self.output_dir, exist_ok=True)

    async def generate(self, markdown_text: str) -> str:
        """Generate PDF from markdown text"""

        # Convert markdown to HTML
        html_content = self._markdown_to_html(markdown_text)

        # Generate PDF
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        pdf_filename = f"vacation_itinerary_{timestamp}.pdf"
        pdf_path = os.path.join(self.output_dir, pdf_filename)

        # Create PDF with custom styling
        HTML(string=html_content).write_pdf(
            pdf_path,
            stylesheets=[CSS(string=self._get_pdf_styles())]
        )

        return os.path.abspath(pdf_path)

    def _markdown_to_html(self, markdown_text: str) -> str:
        """Convert markdown to styled HTML"""

        # Convert markdown to HTML
        md = markdown.Markdown(extensions=['extra', 'nl2br', 'sane_lists'])
        body_html = md.convert(markdown_text)

        # Wrap in complete HTML document
        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vacation Itinerary</title>
</head>
<body>
    <div class="container">
        {body_html}
    </div>
    <div class="footer">
        <p>Generated by Vacation Builder | {datetime.now().strftime('%B %d, %Y')}</p>
    </div>
</body>
</html>
        """

        return html

    def _get_pdf_styles(self) -> str:
        """Get CSS styles for PDF"""
        return """
@page {
    size: A4;
    margin: 2cm;
    @bottom-center {
        content: counter(page) " / " counter(pages);
    }
}

body {
    font-family: 'Helvetica', 'Arial', sans-serif;
    line-height: 1.6;
    color: #333;
    font-size: 11pt;
}

.container {
    max-width: 100%;
}

h1 {
    color: #2c3e50;
    font-size: 28pt;
    border-bottom: 3px solid #3498db;
    padding-bottom: 10px;
    margin-bottom: 20px;
    page-break-after: avoid;
}

h2 {
    color: #2980b9;
    font-size: 20pt;
    margin-top: 25px;
    margin-bottom: 15px;
    page-break-after: avoid;
}

h3 {
    color: #16a085;
    font-size: 16pt;
    margin-top: 20px;
    margin-bottom: 10px;
    page-break-after: avoid;
}

p {
    margin-bottom: 12px;
    text-align: justify;
}

ul, ol {
    margin-bottom: 15px;
    padding-left: 25px;
}

li {
    margin-bottom: 8px;
}

strong {
    color: #2c3e50;
    font-weight: 600;
}

em {
    color: #555;
}

a {
    color: #3498db;
    text-decoration: none;
}

hr {
    border: none;
    border-top: 2px solid #ecf0f1;
    margin: 30px 0;
}

.footer {
    position: fixed;
    bottom: 0;
    width: 100%;
    text-align: center;
    font-size: 9pt;
    color: #7f8c8d;
    padding: 10px 0;
}

blockquote {
    background: #f9f9f9;
    border-left: 4px solid #3498db;
    padding: 10px 20px;
    margin: 20px 0;
    font-style: italic;
}

code {
    background: #ecf0f1;
    padding: 2px 6px;
    border-radius: 3px;
    font-family: 'Courier New', monospace;
    font-size: 10pt;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin: 20px 0;
}

th, td {
    border: 1px solid #ddd;
    padding: 10px;
    text-align: left;
}

th {
    background-color: #3498db;
    color: white;
    font-weight: bold;
}

tr:nth-child(even) {
    background-color: #f9f9f9;
}
        """
